### ISSUE TITLE
[FEATURE] sound: option in menu configuration

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCCosmetics#10]
**I have checked...**

- [x] ...if there are any similar features in other branches
- [x] ...if there are any similar issues
- [x] ...if such a feature is already planned

**Complete description**
Add an optional setting for each GUI button to play a sound when pressed. The configuration could look like this:
```
              sound:
                name: "namespace:my-sound-effect"
                volume: 1.0
                pitch: 1.0
                category: "VOICE"
```

**Reason for feature request**
More customizability
