### ISSUE TITLE
[SUGGESTION] HMC Colors in commands

### ISSUE THREAD

**Issue by itsMarkiS** [HibiscusMC/HMCCosmetics#114]
### Feature Description

for example

/cosmetic apply cosmetic_hat PLAYER red:1
(red being the main color, 1 being the subColor, defined in HMCColor config)
if the HMCColor config is like

```
  red:
    name: "<#D23635><bold>RED"
    baseColor: 210,54,53
    subColors:
      1:
        name: "<#CE263E><bold>Soft Crimson"
        color: "#CE263E"
```

then the color #CE263E would be applied while using the examplified command (/cosmetic apply cosmetic_hat PLAYER red:1)

### Implementation Description

other way to do it was to change HMCColor config, adding a new part in "subcolors" that could be named "data-name"

```
  red:
    name: "<#D23635><bold>RED"
    baseColor: 210,54,53
    subColors:
      1:
        data-name: soft_crimson
        name: "<#CE263E><bold>Soft Crimson"
        color: "#CE263E"
```

so you could use /cosmetic apply cosmetic_hat PLAYER soft_crimson
