### ISSUE TITLE
Add "any action" when a player doesn't have permission 

### ISSUE THREAD

**Issue by NoltoxGit** [HibiscusMC/HMCCosmetics#146]
### Feature Description

Hello,
Would it be possible for the `any: [close]` action to close the menu even if the player doesn't have permission to use the cosmetic?
```yml
    actions:
      any:
        - "[CLOSE]"
 ```
