### ISSUE TITLE
Bobbing Balloons

### ISSUE THREAD

**Issue by GrayHay** [HibiscusMC/HMCCosmetics#23]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

When having a balloon held, it would be nice to have that balloon bob up and down a certain amount defined in config

### Config Changes

```yaml
balloon_bobbing:
  # speed of the balloon bobbing up and down.
  bobbing_speed: 4
  # how high should the balloon go up and down.
  bobbing_distance: 3
```
