### ISSUE TITLE
[FEATURE] Re-implement "remove-cosmetics" action

### ISSUE THREAD

**Issue by Replaycchi** [HibiscusMC/HMCCosmetics#46]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Add back the "remove-cosmetics" action from old HMCCosmetics

```
    action:
      any:
        remove-cosmetics:
          - HAT
          - BACKPACK
          - OFF_HAND
          - BALLOON
          - CHEST_PLATE
          - PANTS
          - BOOTS
```
