### ISSUE TITLE
[FEATURE] Allow trying on cosmetics via wardrobe

### ISSUE THREAD

**Issue by lucian929** [HibiscusMC/HMCCosmetics#55]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Currently, trying on a cosmetic you do not own in the wardrobe is impossible, as you will get a "no permission" message.

A new configuration option should allow users to try on all cosmetics via the wardrobe but not apply them when they exit. 

### Config Changes

config.yml:

```yaml
wardrobe:
  # allow users to "try on" cosmetics via the wardrobe which are unapplied on exit if they do not have the permission.
  allow-trying-on: true
```
