### ISSUE TITLE
[FEATURE] Locked Item/Not showing cosmetics they have permission to.

### ISSUE THREAD

**Issue by Bakayarouz** [HibiscusMC/HMCCosmetics#77]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Pretty much the idea behind is either replace the item in the GUI with a custom pre-defined item/modeldat/lore to display when player does not have the cosmetic permission.

Perhaps some kind of global config if they don't have permission then the display would be

```
LockedItem:
  Item-Model: PAPER
  Model-Data: 41231
  Lore:
  - What the helll boi
  - Boi what the hell
```
So this will be displayed in place of the cosmetic if they have no permission to use it

Or make cosmetics menus only display the cosmetics they have permission to.
